### ISSUE TITLE
Summary of bugs.

### ISSUE THREAD

**Issue by OneMonkeyArmy** [moonglow/flashforge_firmware_tool#3]
I just realise that when i print an object from repetier to The Dremel 3D20, the ETE time display seems accurate, but the ETA is  completely off... Ex. :  ETA 23 17 14 DAY 22 !!!

While the stock thermocouple in the printing head (when not printing since a long time), should display the temperature of the room, it gives me readings between 27 and 28..At the same time I have connected a HT-NTC100K B3950 thermistor to NTC1 and another to NTC2 with some precision resistor of 4.7k pull up to the 3.3v (pin1). They gives different temperature with the presets 11, 61 and 1000.... but more accurate than the thermocouple, reallyb around the room temp. (22 - 23). But the worst part, is that i no longer can upload a new firmware... Here's why: everytime I power it up, it shows the boot images, and just after the marlin logo, the RED SCREEN OF DEATH :  ERR MAX TEMP E2   PRINTER HALTER   PRESS RESET...

I think it is a ONE WAY - DEAD END... what do you think?   Do I throw the printer from the 3rd floor...?  
But I know exaxtly where the Shit Hit The Fan!  When I put back the TEMP_1_PIN to -1 in the file pins_FF_MOTHERBOARD.h (Even if the rem says (-1 means... /* skip checking, change to ADS1118 CH1 */ )    it didn't because i didn't put back the ... #define TEMP_SENSOR_1  to -666 and let it at 1000.. causing the shit to prepare it's trajectory .. in conditionals_post.h around  the lines 680ish and more.. my mistake passed trough the code....  it should not, but it did.... E2 became a custom sensor with no reference define as well as no pin definition.

I was about to give you a lot of small things to do, but I did the big ONE !! That is what happen when you only sleep 2 hours in 2 days... Good night... When I wake up, I  hope to have some good news, but my expectations are very low, consirering the fact that I think it is almost impossible to upload a different firmware... Let me know..

**Comment by moonglow** [comment]
Btw this is firmware encryption tool repo, but anyway.

Can you provide me your build config `Configuration.h` and `Configuration_adv.h` ? It will give me better understanding what you do and what you get ( builds where you get RSOD  ) for your custom build.

>I think it is a ONE WAY - DEAD END... what do you think? Do I throw the printer from the 3rd floor...?

You can recovery your printer via onboard JTAG ( SWD ) interface from _ANY_ state, i use that method to test new firmware and features before release, but your configuration will give me more information and i can simulate such situation on my test motherboard and give you full feedback how you can bring back printer to live. I think it is very hard to kill your printer by software.

>That is what happen when you only sleep 2 hours in 2 days... Good night... 

I think you must don't drive your car or build firmware if you sleep such small amount of time it be dangerous in both case, but anyway i think all be OK ! just provide me your configuration and ( or ) prebuilded firmware images and i will try your case.

**Comment by OneMonkeyArmy** [comment]
здравствуй

Sorry wrong directory! My bad, I was so tired !  Let me explain again with a bit more clarity!

There is somewhere in Marlin a protection that HALT the printer in case of anything goes over a specified temperature. And in my case it triggers right when i boot up the printer, even before i can see the main screen. And i can't do anything else than turn off or reset the printer. It is a red background screen, with yellow text, saying ....  Err: MAXTEMP: E2  /   ORINTER HALTED   /  Please Reset.... as shown on the video... 

https://user-images.githubusercontent.com/84219749/123118773-ec107980-d410-11eb-86e3-713d95b552e0.mp4

What I want to acheive is very simple to explain... Using the current boards, adding the missing components, to be able to add a dual extruder, an heated bed, and controlled enclosure température. (of course, I will change the z axis made of plastic for a custom one in aluminium) .. the reasons for that is a whole other story that we will debate somewhere else, in private.

I will explain again when it happend, and the circumstances. I was testing HT-NTC100K B3950 thermistor on NTC1 (pin PC5) and NTC2 (pin PC4), everything was working perfectly. Then I decided to attribute one of them to the 2nd extruder, instead of the ADS1118 CH1, So i changed this in  pins_FF_MOTHERBOARD.h

#define TEMP_0_PIN                          -1 /* skip checking, change to ADS1118 CH0 */
#define TEMP_1_PIN                          -1 /* skip checking, change to ADS1118 CH1 */
#define TEMP_BED_PIN                      PC5 /* NTC1 4.7k PU */
#define TEMP_CHAMBER_PIN            PC4 /* NTC2 4.7k PU */

for:

#define TEMP_0_PIN                          -1 /* skip checking, change to ADS1118 CH0 */
#define TEMP_1_PIN                          PC5 /* NTC1 4.7k PU */
#define TEMP_BED_PIN                     -1 
#define TEMP_CHAMBER_PIN            PC4 /* NTC2 4.7k PU */

and of course:

i have change in configuration.h

#define TEMP_SENSOR_1         -666

I tried 11 , 61 then 1000

but it didn't worked, so I decide to revert everything to previous values.

I put back the pin number to what it was, but i forgot to put the sensor back to -666. So as explained before (probably very badly! my bad!) if you compile the firmware like this, no error will occur, but if you go to conditionnal_post.h ...  you will see how this ommission was treated... between line 675 to 700,

It end up, defined as ADS1118 CH1, also as TEMP_SENSOR_1_IS_THERMISTOR 1  and TEMP_SENSOR_1_IS_CUSTOM 1.

That was created by conditionnal_post.h, in the lines mentionned above, with the forgotten value of 1000 in #define TEMP_SENSOR_1 instead of -666, when pin is defined as ADS1118 on CH1.

I didn't do it on purpose, it is just bad luck, but conditionals_post.h should have not let it happend. But don't take it as a blame! 

Is it more clear? Am I right?  if not let me know, i will answer all your questions... because, if you can get me out of this dead end, it will be very appreciated. 

if you want to upload the deadly firmware, i have included the version encrypted version for Dremel, but I am not sure it is a good idea....

[Dremel.zip](https://github.com/moonglow/flashforge_firmware_tool/files/6703138/Dremel.zip)

Because the ''RED SCREEN OF DEATH'' never gives me the chance to access the menu, and of course, because printer is halted right after bootup, no chances to acces it by usb. so no way to upload a new firmware. the only thing I know is that microcontroller got SWD (serial-wire debug); TMS/SWDIO is on  pin 105 (PA13) and TCK/SWCLK is on  pin 109 (PA14). But, of all the experiences I got, this I'm a newbie! So ST-link or JTAG, for me is chineese!

If you come to another conclusion, let me know as soon as possible, because i'm already shopping for another board, of course, i have on hand many other controllers, like SKR 1.4 turbo and lcd screens, that will be very easy to acheive everything but it is not my goal.

Until then, i will go back to my monster... I will make from scratch 2x 80w hotend 3mm, from a block of aliminium in my shop today with custom heatbreak as well as custom heatsink, because i have received 2 extruder with a geared ratio of 3:1, with nema17 2A with a torque of 59Ncm x 3 (because of the gears) I think i'm goona be able to push enough filament, even with high speed and a nozzle of 1.2mm per head.

Thanks again for taking care of the problems of the old and crazy Monkey!

But you can put that on the side, and jump to something else I have in mind since long time. And the timing should and would be perfect! And I know that I have found the right guy for that, I don't know your name, or your age, or your background, but I can see the Will, the skill,  determination and most important, the persistance in your work. I don't know what you do for money, but it is not here that someone can make money. I always belived in '' IF YOU ARE GOOD AT SOMETHING, NEVER DO IT FOR FREE ''  I had a lot of good ideas in my life, I tried some of them, and most of them brought a good amount of money, and a few, brought piles of money! Orm maybe you are already rich and don't give a damn about making more!

I will continue, as soon as possible to tell you more on your private email, that you can send me on one of my email... dvamontreal@hotmail.com

The ball is in your hand player!

**Comment by moonglow** [comment]
Thank you for explanation ! Btw this is not a bug, but you absolutely legal can kill Marlin with specific config.... In most cases you can't mix ADS1118 ( or other external extruder temp controllers ) + ADC as extruder temp source because if you define ADS1118 other will not uses. And why you do not want to use builds for dual head printers ? As example for FF Dreamer you need to add second extruder K-type thermocouple ( ADS1118 is two channel K-type thermocouple controller ) and NTC sensors for bed and chamber and thats all..

>There is somewhere in Marlin a protection that HALT the printer in case of anything goes over a specified temperature.

I understand it ( btw for test purpose i really recommends disable thermal protection in case you do experements with firmware ) as exmple you need to comment ( `Configuration.h` )
`THERMAL_PROTECTION_HOTENDS`
`THERMAL_PROTECTION_BED`

>Is it more clear? Am I right? if not let me know, i will answer all your questions... because, if you can get me out of this dead end, it will be very appreciated.

Yep, i understand your main goal and i think you will do all OK next time, i will try tomorrow give you a solution for your situation ( we have a time shift due timezone and looks like our activity is shifted :) ) 

>If you come to another conclusion, let me know as soon as possible, because i'm already shopping for another board, of course, i have on hand many other controllers, like SKR 1.4 turbo and lcd screens, that will be very easy to acheive everything but it is not my goal.

Dremel or FF motherboard is really nice. I do not recommend you to change it, because new boards => new problems and so on, nothing is ideal in our lives.

>And I know that I have found the right guy for that, I don't know your name, or your age, or your background, but I can see the Will, the skill, determination and most important, the persistance in your work. 

Thank you, my main goal is making some cool things that will be needed by other people too, but it is also a part of my portfolio and my way to find some cool people too.

>Orm maybe you are already rich and don't give a damn about making more!

Hahaha ) Nope, but i also wish to make it true :)

**Comment by moonglow** [comment]
@OneMonkeyArmy Hi !

Thermal protection works really well and doesn't allow me to find a way to stop it :( But anyway you just need to buy a very cheap STLink programmer clone to read MCU memory ( i will fix MCU dump for you and you will have unbreakable printer what you can't kill ever and it also can be recovered from any software states ), i also tried to put MCU to internal bootloader mode, but it does not work, maybe it was disabled after software bootloader was flashed on factory. So you need to buy STLink ( you can choose any seller you want or buy it local ): [AliLink](https://aliexpress.ru/item/32887597480.html), next please read that article: [Read MCU flash](https://github.com/moonglow/FlashForge_Marlin/wiki/Backup-printer-firmware) you also no need soldering skills to make it, just few DuPont wires and STM32CubeProgrammer utility.

**Comment by OneMonkeyArmy** [comment]
Sorry for the delay to answer you, but Emergency are priority to projects!!

Thank you for helping me in my mistake... I have found one I can have very fast from amazon, (because I am far from aliexpress!)
if you can tell me that it is ok.. i order right away...

https://www.amazon.ca/ST-Link-Programming-Emulator-Simulator-Downloader/dp/B079HXL4SS/ref=sr_1_13_sspa?dchild=1&keywords=Link+Stlink+ST-Link+V2+for+STM8+STM32&qid=1625194165&s=industrial&sr=1-13-spons&psc=1

**Comment by moonglow** [comment]
>Sorry for the delay to answer you, but Emergency are priority to projects!!

No problem, hobbies project must has lowest priority to get better real life performance :)

>I have found one I can have very fast from amazon, (because I am far from aliexpress!)

I think that adapter is a little ( ok ok not a little ) OVERPRICED if it OK for you, you can buy it from Amazon, but this company just trade chinese clones from Ali :)

**Comment by OneMonkeyArmy** [comment]
I don't care about the price, what is important is the delivery time, with amazon, I will get it in 3 days, with aliexpress, I will get it in 3 weeks!.. I will order Now... Thanks again.. As soon I will have an hour, I will send you an email, regarding the project I want to tell you.. soon!

**Comment by OneMonkeyArmy** [comment]
I have received it, and now what I do?

**Comment by moonglow** [comment]
I think case closed. Thanks for assistance
