### ISSUE TITLE
Unable to execute binary files

### ISSUE THREAD

**Issue by MetalDracon** [moonglow/flashforge_firmware_tool#4]
While using the program on Ubuntu I was able to use it to encrypt the files a couple of weeks ago but after applying some system updates ( I don't know everything that updates I allow the updater to update everything), the command no longer encrypts the firmware.  Instead I receive an error that ff_fw_tool is unable to execute binary files. So far I have tried changing the file type of the ff_fw_tool from no type to .exe and .sh and have gotten the same error each time. I have also regenerated the tool using the main.c file but so far nothing has worked.

**Comment by moonglow** [comment]
Hi @MetalDracon !

Thats question is not related to my software i think... it is more like for general dev or OS users question... but you can check compiled binary flags and if it does not has 'executable' flag set you can set it you own with something like that `chmod +x ./file_name`

**Comment by MetalDracon** [comment]
Thank you for the help. After some further investigation I found that my command had the wrong syntax which was causing the error. I apologies for lodging my inexperience as an issue.
